### ISSUE TITLE
"RangeError: Invalid string length" while updating Element Props

### ISSUE THREAD

**Issue by mohasarc** [codelab-app/platform#1905]
## Current Behavior

After changing the Element props a few times this error shows up as demonstrated in the attached video. After some debugging I noticed that the length of `className` field gets too large that string concatenation is not able to handle anymore. Additionally, it seems to always happen when `mergeProps` is called from `Renderer.processPropsForRender`
 
## Expected Behavior
`className` field should not get that large.

## Steps to Reproduce

https://user-images.githubusercontent.com/51242349/194308888-2bbcbf3f-8ce3-404a-8615-d6c3e52b3bf5.mp4

**Comment by melhamin** [comment]
I tried a lot but haven't been able to reproduce the issue. @mohasarc can you try again?

**Comment by mohasarc** [comment]
Yeah I could reproduce it. It seems to happen when using `MuiAutocomplete` but I think it can potentially happen with other components too. Here is how I reproduced it:


https://user-images.githubusercontent.com/51242349/200110134-f3296f10-6001-48fc-88bb-24d5b0c72e9a.mp4

**Comment by melhamin** [comment]
Strangely, same steps do not cause error for me. Could it be that one of those components is corrupted and has a very long `className` in your db? @mohasarc Can you reset your db and try again?

**Comment by mohasarc** [comment]
After this PR #1968 was merged it got harder to reproduce the issue; the reason is that before the PR, and on mouse move the elements would rerender. However, It is still possible to reproduce using the way demonstrated in the issue description: just add and remove options array to element props a few times. @melhamin

**Comment by melhamin** [comment]
@mohasarc I couldn't reproduce it even by changing options. If you are still getting the error on the latest master, can you take over the issue and try to fix it yourself?

**Comment by mohasarc** [comment]
That's interesting, it could be because of the differance in the hardware. Sure, I'll take over.

**Comment by mohasarc** [comment]
I don't seem to be able to replicate this anymore. it might have been fixed by some PR. I'm closing the issue for now, we can reopen later if it showed up.

**Comment by mohasarc** [comment]
I don't seem to be able to replicate this anymore. it might have been fixed by some PR. I'm closing the issue for now, we can reopen later if it showed up.
