### ISSUE TITLE
Add "children" prop for atoms

### ISSUE THREAD

**Issue by vladyslav-polishchuk** [codelab-app/platform#2145]
## Description
This is a prerequisite for #1767.
Add "children" prop to atoms so that it is possible to specify child elements using expressions.
when `allowedChildren` property in atom is not empty append an new field to atom api of type `RenderNode` where `key=children` . because this interface is passed to props form an new input will of type `RenderNode` will be displayed. we may have to teak `renderChildren` to handle children rendering

**Comment by webberwang** [comment]
@vladyslav-polishchuk is this still relevant?

**Comment by vladyslav-polishchuk** [comment]
@webberwang, this was a prerequisite for the task about the possibility of rendering children inside of the component, but we were able to accomplish that goal without completing this task.
On the other hand, having the possibility to specify children on an element in the builder tree not only by adding child nodes to that element in the builder tree but also by expression on props form also gives additional flexibility. However, I did not have such a use-case while I was creating the Portfolio demo app. @jethrocabaluna, do you have scenarios when you may need this feature in your Store application?
If not - we may cancel this issue for now and re-open only if we find a use-case when this is useful.

**Comment by webberwang** [comment]
It generalizes to binding prop to nested elements in a component right? We use expression to bind any prop field we want, which could be a children key

**Comment by vladyslav-polishchuk** [comment]
Not sure I understand, could you expand a little bit more?
