### ISSUE TITLE
Refactor draggable ref to not use setTimeout

### ISSUE THREAD

**Issue by webberwang** [codelab-app/platform#2161]
## Description

We want a different implementation to not use setTimeout here https://github.com/codelab-app/builder/pull/2157/files#r1067316830

Please suggestion some implementation ideas so we can decide on what is the best approach.

**Comment by ky213** [comment]
could someone please help me reproduce this error?

**Comment by ky213** [comment]
I just removed the setTimeout function and things seem to be working properly, especially the AntDesignImage atom
<img width="1184" alt="image" src="https://user-images.githubusercontent.com/22745510/217233083-6f0f49ae-ff9d-436f-8846-1f8082702a86.png">
<img width="1415" alt="image" src="https://user-images.githubusercontent.com/22745510/217233447-846c147d-1bfc-4bdc-9ec1-87758ac50f7c.png">
