### ISSUE TITLE
Add description tooltip for atom props

### ISSUE THREAD

**Issue by vladyslav-polishchuk** [codelab-app/platform#2172]
## What Feature Can Be Enhanced?
Currently, after the seed command is run we get a lot of Ant Design atoms available. Most of them contain descriptions about the fields but this information does not seem to be displayed for the user anywhere.

I suggest wrapping the title of each prop with the tooltip component and displaying the property description (or add a question mark after the title and display the tooltip when user hovers over it)

<img width="359" alt="Screenshot 2023-01-13 at 18 49 40" src="https://user-images.githubusercontent.com/74900868/212386807-d1e51534-abcd-4171-b1c6-ec6bd504b352.png">

**Comment by webberwang** [comment]
That seems to be the fastest implementation let's go with that first

**Comment by mohasarc** [comment]
To have tooltip we'd need to:

1. Implement a custom version of each unifroms field and wrap the original component with a tooltip.
2. However, now we need to access the description value in the custom component to pass it to the tooltip. To be able to do that we'd need to first add it to the json schema. like follows: 

type-schema.factory.ts
![image](https://user-images.githubusercontent.com/51242349/222241536-72e38ff0-3c14-407c-9196-881532267550.png)

in this case we added the description to a new field called `help`

3. access `help` field's value and pass it to the tooltip.

A complete implementation of the custom field would look like this

![image](https://user-images.githubusercontent.com/51242349/222242889-dac0d2ec-dd37-4315-bc4c-2dd2ebd2e4a6.png)
