### ISSUE TITLE
Investigate if we can migrate to SWC compiler 

### ISSUE THREAD

**Issue by vladyslav-polishchuk** [codelab-app/platform#2186]
## What Feature Can Be Enhanced?
New versions of Next.js use SWC compiler out of the box, which is based on Rust and is much more performant that babel - https://nextjs.org/docs/advanced-features/compiler#why-swc

Investigate if we can migrate to it without much efforts

**Comment by webberwang** [comment]
It’s not possible until babel supports SWC

**Comment by vladyslav-polishchuk** [comment]
> It’s not possible until SWC supports babel

As far as I understood, SWC is a replacement for babel, not an extension of it. So the question is more like this: does it support all the options that babel does? Or at least a subset of options that our project relies on

**Comment by webberwang** [comment]
> > It’s not possible until SWC supports babel
> 
> As far as I understood, SWC is a replacement for babel, not an extension of it. So the question is more like this: does it support all the options that babel does? Or at least a subset of options that our project relies on

Right, I mean to say support what babel did before, so tailwind etc

**Comment by webberwang** [comment]
https://blog.railway.app/p/twin-macro-tailwind-migration

could possibly be done if we remove emotion
