### ISSUE TITLE
Mobx-keystone upgrade will require frozen data to be serializable 

### ISSUE THREAD

**Issue by assimhabeek** [codelab-app/platform#2193]
## Current Behavior
After https://github.com/codelab-app/builder/pull/2190 which upgrades (mobx-keystone) is merged we won't be able to pass functions into frozen data any more this will mostly effect how store/actions are working
## Video Showing Bug

https://user-images.githubusercontent.com/33001357/213867278-08d82bdf-32cb-409f-ac43-e4dda89e8b19.mp4

**Comment by webberwang** [comment]
@assimhabeek  Can't we pass a function in the form of a string?
