### ISSUE TITLE
Take the site live to production, data migration etc

### ISSUE THREAD

**Issue by webberwang** [codelab-app/platform#2197]
## Description

We can currently run seeder using the cli app with production env to seed those data. But once taken live we won't be able to reset the data.

The migration seeder script should already not override old data, but we should still have some basic data backup strategy.

- [x] Seed production data

- [x] Test out builder in production, especially preview mode 

- [x] Propose a production data backup strategy (lowest priority)

This should be very basic, it can be manually done daily.

- [x] Auth0 social login provider needs to be setup for production (Google only for now)
@webberwang I've added it, still need testing. Can't test because `/apps` not working on live site

**Comment by vladyslav-polishchuk** [comment]
Daily backups are set up on Aura, so the production data backup strategy has already been implemented. Closing the issue as solved
<img width="1013" alt="Screenshot 2023-04-02 at 19 02 52" src="https://user-images.githubusercontent.com/74900868/229367720-52e0b5bf-907a-4835-ba75-e78b416b9848.png">
