### ISSUE TITLE
Custom Field for defaultValues on the create/update field modal for array types

### ISSUE THREAD

**Issue by jethrocabaluna** [codelab-app/platform#2208]
## What Feature Can Be Enhanced?
We have a custom field made for the `defaultValues` if it is an array in the create/update field form but the built-in validations from uniforms does not work properly.
In this [PR](https://github.com/codelab-app/builder/pull/2199), theres a custom schema made for the defaultValues but the errors doesn't show on the uniforms fields for the `defaultValues`.

When a new item is added, the initial value shows the default for that primitive type, but in the actual model it is still undefined, hence, it will have an error on the validations upon submitting. The workaround is to manually enter a value so that its value changes in the model.

https://user-images.githubusercontent.com/27695022/214823921-02eb5ccf-c485-4977-b021-98df4c33c24c.mp4

A solution could be to transform the undefined values to the default values of whatever is the item type for the array, but there may be too much overhead, and may have to create some kind of recursive function if it is an array of array (or more array).

**Comment by mohasarc** [comment]
similar to #2423 and will probably be fixed with it.
