### ISSUE TITLE
Personal portfolio website

### ISSUE THREAD

**Issue by webberwang** [codelab-app/platform#2224]
## Description

We'll be copying other websites to test out our own platform.

Re-create https://leerob.io. 

- [x] Create all the pages, link each page to domain whitelist (your own domain). Render the title on each page only
- [ ] Test out menu link navigation
- [ ] Responsive menu, tablet mobile view should go on top
- [x] Add all simple content with antd grid layout when needed for all pages
- [x] Add github sign in
- [x] Blog page link to supabase

**Comment by vladyslav-polishchuk** [comment]
Not fully implemented. Only a tiny part of the app was created which most probably will not be compatible after the last major frontend refactoring
