### ISSUE TITLE
CSS styles do not apply for _app page

### ISSUE THREAD

**Issue by vladyslav-polishchuk** [codelab-app/platform#2236]
## Video Showing Bug

https://user-images.githubusercontent.com/74900868/216838277-7b8133b3-d6bd-496c-b43e-100c24d2ef61.mov

**Comment by melhamin** [comment]
@vladyslav-polishchuk can you explain what the expected behavior is here? Apart from the `css` that should be passed properly, do we expect other pages to have the styling of the `_app`?

**Comment by vladyslav-polishchuk** [comment]
_app page is a wrapper around any other page, just like _app page in Next.js, so the issue when I add some atom on _app page, apply some css for that atom (this atom is going to be rendered on any other page now) the css does not apply for that atom on other pages. E.g. if I added a red button in _app page - it will lose the red color when rendered on other pages
