### ISSUE TITLE
Impossible to use AntDesignMenu atom

### ISSUE THREAD

**Issue by vladyslav-polishchuk** [codelab-app/platform#2237]
## Current Behavior
AntDesignMenu supports 2 ways to create a Menu component:
1. Recommended: Specify `items` property array. But this property is absent on AntDesignMenu atom.
And additional problem exists: `items` is an array of objects which may contain ReactNodes as values:
<img width="548" alt="Screenshot 2023-02-05 at 21 05 02" src="https://user-images.githubusercontent.com/74900868/216842149-36c8560c-ef9b-40bb-af05-b5b42838dbb5.png">
The platform does not support ArrayTypes of such a complex structure.

2. Obsolete: Use Menu component and specify Menu.Item as children. But currently no Menu.Item atoms exists.

As a result - it is impossible to create Menu element

**Comment by mohasarc** [comment]
It seems like we actually can create AntDesignMenu atom, here is how:

1. create a new type for menu items `AntDesignMenuITemType` then create an array of that type `Array<AntDesignMenuITemType>`

![image](https://user-images.githubusercontent.com/51242349/228808470-6af9a99f-6855-4f41-85f3-405e03487dba.jpg)

2. add a new field to `AntDesignMenu API`

![image (1)](https://user-images.githubusercontent.com/51242349/228808646-d7577426-3902-45aa-9782-a7e0de94db6c.jpg)

3. add some values

![image](https://user-images.githubusercontent.com/51242349/228808837-51a1a1ad-9e44-4621-862c-ea58c38b1f88.png)


Yet it would be better if these types are created during the seeding process. Also icon didn't seem to work but that could be related to #2415
