### ISSUE TITLE
Remove page/element slug

### ISSUE THREAD

**Issue by assimhabeek** [codelab-app/platform#2246]
## What Feature Can Be Enhanced?
Remove `slug` from page/element and force the following rules for page/elements names:

- Should start with a letter and consist of letters, numbers and space.
- Make sure it is unique,  just like we did with slug.
- To use in object keys/urls replace space with either underscore or dash

**Comment by mohasarc** [comment]
Do we want to completely remove page/element slugs from backend too? or internally compute them? Also, what about app slugs?
