### ISSUE TITLE
Use only the Builder as droppable element

### ISSUE THREAD

**Issue by ky213** [codelab-app/platform#2248]
## Description

Hello,

It seems that all of the atoms in our builder are set to be droppable and draggable at the same time, this is not good for performance and may cause a lot of issues. 
In the explorer, we already have the ability to nest a child, so I think this is fair enough to implement any desired parent/child relationship.
As per my discussion with Webber, I think we should only set the main builder as droppable and the rest of atoms and components as draggable. 

The discussion is open guys!

**Comment by webberwang** [comment]
I think could be good in the meantime to disable droppable until we find a way to configure which atom is droppable

**Comment by ky213** [comment]
sure, I can start by naming "container" atoms like Raw, Col, Card ...etc

**Comment by webberwang** [comment]
Could add an unDroppable field to atom schema

**Comment by nettohadi** [comment]
I agree with adding the `unNestable` to the Atom schema. What about user-created components? are they always droppable?

**Comment by nettohadi** [comment]
So, what happens if users try to drop an atom into non-droppable atom? Do we show an error message or something?

**Comment by webberwang** [comment]
> So, what happens if users try to drop an atom into non-droppable atom? Do we show an error message or something?

It shouldn't be possible, the user wouldn't be able to do it in the UI

**Comment by webberwang** [comment]
> I agree with adding the `unNestable` to the Atom schema. What about user-created components? are they always droppable?

That depends on the existence of a children property. This becomes a bit complicated though, since what about props with ReactNode, should those be droppable

**Comment by nettohadi** [comment]
> > So, what happens if users try to drop an atom into non-droppable atom? Do we show an error message or something?
> 
> It shouldn't be possible, the user wouldn't be able to do it in the UI

Correct me if I am wrong, I assume that users can still drag and drop an Atom anywhere. However, if the target Atom isn't droppable, nothing happens, correct? Perhaps, instead of showing nothing, we could provide feedback informing the user why they can't nest that Atom.

**Comment by nettohadi** [comment]
> > I agree with adding the `unNestable` to the Atom schema. What about user-created components? are they always droppable?
> 
> That depends on the existence of a children property. This becomes a bit complicated though, since what about props with ReactNode, should those be droppable

Hmm, I need to learn how we implement drag and drop first before commenting on this. I faced similar issue in my project long ago. I might have a solution for this.

**Comment by webberwang** [comment]
> > > So, what happens if users try to drop an atom into non-droppable atom? Do we show an error message or something?
> > 
> > 
> > It shouldn't be possible, the user wouldn't be able to do it in the UI
> 
> Correct me if I am wrong, I assume that users can still drag and drop an Atom anywhere. However, if the target Atom isn't droppable, nothing happens, correct? Perhaps, instead of showing nothing, we could provide feedback informing the user why they can't nest that Atom.

Rather than error message, I think droppable areas could have a different color outline indicating that it can. The error message wouldn’t be too helpful, but just that X can’t be nested under Y

**Comment by nettohadi** [comment]
> > I agree with adding the `unNestable` to the Atom schema. What about user-created components? are they always droppable?
> 
> That depends on the existence of a children property. This becomes a bit complicated though, since what about props with ReactNode, should those be droppable

Could you elaborate more on the existense of a children property? I am not sure how it looks like in the builder. Can we add custom children in builder?
