### ISSUE TITLE
Create atom to render MD content

### ISSUE THREAD

**Issue by vladyslav-polishchuk** [codelab-app/platform#2269]
## Description
For applications similar to blogs it is important to have the markdown renderer atom. Otherwise, it will be required to manually create each blog page using builder, which is much longer.

**Comment by webberwang** [comment]
Could we integrate a wysiwyg atom instead?

**Comment by vladyslav-polishchuk** [comment]
This may be a good option

**Comment by amrmuhamedd** [comment]
@webberwang what is wysiwyg atom ?

**Comment by webberwang** [comment]
an atom with wysiwyg editor

**Comment by amrmuhamedd** [comment]
@webberwang  @vladyslav-polishchuk 
we use Ql to edit paragraph atoms it will be an atom like Antdesign paragraph? if no what will be the difference 
I see this editor: https://ckeditor.com/ckeditor-5/demo/feature-rich/
are we need something like this?
