### ISSUE TITLE
Add "Script" atom to allow load external libraries on user pages

### ISSUE THREAD

**Issue by vladyslav-polishchuk** [codelab-app/platform#2271]
## Description
For example, to create a demo app in #2224 I need to load the supabase library.
This may be also beneficial for other cases, like custom analytics, ads, widgets, etc.

**Comment by assimhabeek** [comment]
```
  [IAtomType.Script]: dynamicLoader(() =>
    import('@codelab/frontend/platform/atoms').then((mod) => mod.CodelabScript),
  ),
```
@vladyslav-polishchuk script atom already exist

**Comment by vladyslav-polishchuk** [comment]
@assimhabeek, @webberwang  Any hints on how I can use this in production? Or should I update the seeder so that it imports it as an atom to the DB?

**Comment by webberwang** [comment]
should probably add as atom under html atoms
