### ISSUE TITLE
Allow users to load custom fonts for their apps

### ISSUE THREAD

**Issue by vladyslav-polishchuk** [codelab-app/platform#2290]
## Description

Builder uses Montserrat, Nunito, and Roboto fonts, but this may be not what user wants for their apps. Allow users to load custom fonts into the applications.

**Comment by webberwang** [comment]
Related to 

- https://github.com/codelab-app/platform/issues/2271 

right?

**Comment by vladyslav-polishchuk** [comment]
I have not used Script atom yet, not sure how it works. Does it allow to pick type ("script"/"link"), or do you mean just programmatically insert a link tag from the script?
