### ISSUE TITLE
Cleanup unused dependencies in package.json

### ISSUE THREAD

**Issue by vladyslav-polishchuk** [codelab-app/platform#2350]
## What Feature Can Be Enhanced?
package.json has a huge list of dependencies, but there are several that are not used anymore.
- cleanup unused dependencies
- move all typescript dependencies to "devDependencies"

**Comment by webberwang** [comment]
Do you mean for the main repo, or for the production site

**Comment by vladyslav-polishchuk** [comment]
I mean for the main repo, so that no packages that are no longer used are installed when executing `yarn` locally or on CI
