### ISSUE TITLE
Fix unit specs renderer & others

### ISSUE THREAD

**Issue by webberwang** [codelab-app/platform#2419]
## Description

Possibly can use store setup as our main app, meaning only services

![create-root-store_ts_—_platform](https://user-images.githubusercontent.com/26264925/228466906-9da852fc-ceef-4cec-b525-2f54935e9938.jpg)

This way we can re-use some create methods

![component_service_ts_—_platform](https://user-images.githubusercontent.com/26264925/228466737-32afda30-f57e-41bb-9a68-9d38166a2c7e.jpg)

We just have to stub out the repositories since we're doing a unit specs without database connection

https://jestjs.io/docs/jest-object#jestspyonobject-methodname

- [ ] Revert DTO changes

![image](https://user-images.githubusercontent.com/26264925/229257150-f5f27c4b-852f-48bb-b32f-603b82f316dd.png)

We shouldn't have to modify the dto to make the specs work

**Comment by vladyslav-polishchuk** [comment]
Done
