### ISSUE TITLE
Stabilize e2e tests on CI

### ISSUE THREAD

**Issue by vladyslav-polishchuk** [codelab-app/platform#2499]
## Current Behavior
Currently, 2 tests are failing from time to time on CI:
tag.cy
providerPage.cy

Need to investigate and make them more stable.
Example of failed job - https://app.circleci.com/pipelines/github/codelab-app/platform/9129/workflows/7046c305-daf5-4d1d-b480-b99aeb34079e/jobs/31413/steps

**Comment by webberwang** [comment]
Yeah I was seeing this too
