### ISSUE TITLE
Upgrade to node v18

### ISSUE THREAD

**Issue by jethrocabaluna** [codelab-app/platform#2511]
## What Feature Can Be Enhanced?
We should enforce to use node v18 (or maybe consider v20 too as there is an upcoming LTS for v20) since v16 will be EOL this year in September - https://nodejs.org/en/blog/announcements/nodejs16-eol

**Comment by webberwang** [comment]
yeah 18 is good since Vercel supports that as well 
![image](https://user-images.githubusercontent.com/26264925/233331027-8d991061-38f6-4372-9370-4387b0197c1a.png)
