### ISSUE TITLE
When updating an element, it infinitely retries if it failed

### ISSUE THREAD

**Issue by jethrocabaluna** [codelab-app/platform#2512]
## Current Behavior
Noticed this when my account token expired, then I tried updating an element name and it just infinitely retries.

## Video Showing Bug

https://user-images.githubusercontent.com/27695022/233310856-2f877ae8-f51c-4eee-9487-822e2a4865c8.mp4

**Comment by webberwang** [comment]
This issue would be closed by https://github.com/codelab-app/platform/issues/2149

Closed by #2149
