### ISSUE TITLE
UI issues after migration to AntD 5 version

### ISSUE THREAD

**Issue by vladyslav-polishchuk** [codelab-app/platform#2521]
## Video Showing Bug

https://user-images.githubusercontent.com/74900868/233794711-757e040a-7a2c-4c33-9d88-0bbc9cc4b37e.mov

**Comment by vladyslav-polishchuk** [comment]
Currently, two not resolved problems exist:
1. Header height and padding issues:
<img width="931" alt="Screenshot 2023-04-24 at 22 26 28" src="https://user-images.githubusercontent.com/74900868/234109197-b306bb43-1280-4921-87f0-8093cc37f36c.png">
But currently, this is not possible to solve this by ConfigProvider (see https://github.com/ant-design/ant-design/issues/38975 for more details). So in order not to fix this in all places in the product manually I guess we can wait for the antd team to allow customize it over ConfigProvider.

2. Uniforms package is using antd of version 4 under the hood and it looks like it currently does not support vertical forms and all the inputs are displayed to the right of the label, on the same row. I will try to workaround this, but maybe also will need to wait for support of antd5 for uniforms
<img width="527" alt="Screenshot 2023-04-25 at 09 36 17" src="https://user-images.githubusercontent.com/74900868/234207424-e8760e94-de2d-4060-89fd-5bd1e658ea40.png">

**Comment by vladyslav-polishchuk** [comment]
Created an issue for uniforms package - https://github.com/vazco/uniforms/issues/1259

**Comment by webberwang** [comment]
> Created an issue for uniforms package - [vazco/uniforms#1259](https://github.com/vazco/uniforms/issues/1259)

Nice, we can track that issue
