### ISSUE TITLE
Builder layout enhancements

### ISSUE THREAD

**Issue by mohasarc** [codelab-app/platform#2566]
## What Feature Can Be Enhanced?

1. Move `Explorer` and `Store` into the left sidebar to open up more space for the element trees.
2. Make `Page` and `Component` trees to be in different tabs (replacing of `Explorer` and `Store`) so we have even more space per tree.
3. Keep the builder visible when navigating to `pages`.
4. Remove `builder` tab from the sidebar; clicking on the app would immedietly open the first page.
5. create a sidebar on the right and move `Inspector` and `Component` tabs into it.
6. rename `Component` on the right to `Prebuilt Components` and `Component` on the left into `Custom Components` to avoid confusion.

The changes are summarized in the following image:

![image (6)](https://user-images.githubusercontent.com/51242349/235219780-b88da8f8-17e8-4dc6-9b9e-6ca38754cc9e.jpg)

Here is how the final result would roughly look like:

![New Project (1)](https://user-images.githubusercontent.com/51242349/235295418-7afa8eaa-b5d1-4ee5-9a34-232f4e614cc9.jpg)

**Comment by webberwang** [comment]
- Having these tabs under the sidebar page makes it more organized, can be though of as nested structure.
- Moving them to top level makes us lose the structure, and the tabbed layout isn't unique to our UI
 
![Cursor_and_Mouse_Highlight_Overlay](https://user-images.githubusercontent.com/26264925/235298429-a6523dca-64a5-462d-b74c-df159974109e.jpg)

- I do agree the Page/Component tab can be moved elsewhere
- A right sidebar seems like would make the UI too complicated (and too different from other builders)
