### ISSUE TITLE
Consolidate builder/page tabs to a single pages tab

### ISSUE THREAD

**Issue by mohasarc** [codelab-app/platform#2585]
- Instead of navigating to another page when clicking on the `pages` sidebar tab, we'd only open a side panel showing the pages.
- Remove the `Builder` tab. Opening the app would open the builder for the first page by default.

#### Current: clicking the app redirects to pages and builder is not visible. 

![image](https://user-images.githubusercontent.com/51242349/236145803-96496910-2b87-4cf4-905f-c1c74fff7dac.png)

#### Expected: clicking the app redirects to the builder of the first page, and pages tab is a side panel.

![image (8)](https://user-images.githubusercontent.com/51242349/236145891-81606d62-d750-496f-8ada-13186d1b0571.jpg)

**Comment by webberwang** [comment]
The idea is that apps and pages would have different dashboard layouts. The apps would use a workspace dashboard, while the pages would use a builder dashboard
