### ISSUE TITLE
Not all elements are highlighted in builder

### ISSUE THREAD

**Issue by vladyslav-polishchuk** [codelab-app/platform#2603]
## Current Behavior

When for example AntDesignAnchorLink is selected - no highlighting appears for it in builder

## Video Showing Bug

https://user-images.githubusercontent.com/74900868/236646502-4aa101c1-aa3d-4bf6-ac4e-85073edae1b7.mov

**Comment by amrmuhamedd** [comment]
@vladyslav-polishchuk 
it didn't append data-element-id for ant design anchor  and append data-element-id for antd button and the two use atom factory it looks ood
do you know why?
![image](https://github.com/codelab-app/platform/assets/47860740/ccc05d5f-1e3d-41b0-b517-3f22dd32b0e0)
