### ISSUE TITLE
Timeout error on attempt to import an app

### ISSUE THREAD

**Issue by vladyslav-polishchuk** [codelab-app/platform#2626]
## Current Behavior
When an attempt to import an app is done on production build, it may take longer than the 60s limit and the server returns a 504 error with `FUNCTION_INVOCATION_TIMEOUT` status

## Video Showing Bug

https://github.com/codelab-app/platform/assets/74900868/5e7ee7c0-de27-43f5-af7a-25fa93b42934

**Comment by webberwang** [comment]
`The maximum execution timeout is 10 seconds when deployed on a Personal Account (Hobby plan). For Teams, the execution timeout is 60 seconds (Pro plan) or 900 seconds (Enterprise plan).`

Solution could be to send the command to a queue, then the queue would communicate with vercel
