### ISSUE TITLE
Add separate property to store transpiled expression

### ISSUE THREAD

**Issue by vladyslav-polishchuk** [codelab-app/platform#2641]
## What Feature Can Be Enhanced?
Properties of type ReactNode support expressions with JSX inside for advanced control over what is rendered. Currently, we use `sucrase` transpiler and transpile expressions on the fly. The problem is that it is expensive (to load the transpiler and to do this transpilation on the fly when an element is rendered). The goal is to transpile expressions with JSX when it is created/edited in the builder, so that the production user app do not need to do nothing but render already transpiled (possibly event minified) expressions code.

currently expressions are stored as-is in our database. Under as-is, I mean source code that browsers may not understand (with JSX, etc). And current approach is to transpile it to understandable code just before rendering the corresponding element. This has two drawbacks - always need to load the transpiler module (which is quite a big size) and do transpilation, which is also time-consuming. This is not a big problem for the builder, but when the user created an app and deployed it to production, we will still need to do these two steps to render his application. The idea is to have two separate properties: one with the raw source code (this will be displayed and edited in builder), and the second one with transpiled code. Whenever the source code is edited - we update transpiled value as well. This way when running the user app in production we may use only the trasnpiled value

**Comment by webberwang** [comment]
@vladyslav-polishchuk 

Just to clarify the task, we're modifying the `Prop.data` model such that

```
{
  "icon": "some JSX string"
}
```

becomes

```
{
  "icon": {
    "raw": "",
    "transformed": ""
  }
}
```

For 

```
{
 "icon": "some-id-pointing-to-reactnode"
}
```

We wouldn't need to process since it uses code to render, which is already pre-built by Vercel? How come the JSX string doesn't get pre-built by Vercel?

Or is this only for the runtime builder, where production it doesn't matter since everything gets built anyways?

**Comment by webberwang** [comment]
Thanks for clarification, wouldn't this issue make this issue obsolete?

- https://github.com/codelab-app/platform/issues/2662

When we want to use some React code, we would just create a custom atom/component

**Comment by vladyslav-polishchuk** [comment]
> Thanks for clarification, wouldn't this issue make this issue obsolete?
> 
> * [Creating a component from external resources #2662](https://github.com/codelab-app/platform/issues/2662)
> 
> When we want to use some React code, we would just create a custom atom/component

If we would not have jsx inside of ReactNodeType/RenderPropTypes after that issue implementation, then yes, no need to do anything. We can put this one on hold to see the result of #2662 and then decide
