### ISSUE TITLE
CI is not running all e2e tests

### ISSUE THREAD

**Issue by jethrocabaluna** [codelab-app/platform#2651]
## Current Behavior
Just noticed that when checking the e2e tests being ran in parallel, the files are all the same, and its not all the files at all.

I think what is supposed to happen is that the e2e files should be different in all parallel run, and ALL e2e files are tested.

This causes some failing e2e tests to get through and be merged.

## Video Showing Bug

Checking the latest PR merged with success e2e tests

https://github.com/codelab-app/platform/assets/27695022/fe22d572-93e9-41ea-80b6-fe17c697d764

**Comment by webberwang** [comment]
It appears cypress cloud reports the error, but does not get shown up in circleci
