### ISSUE TITLE
Cannot access custom component's edit panel with one click on edit button

### ISSUE THREAD

**Issue by mohasarc** [codelab-app/platform#2695]
## Current Behavior

for some reason, it is required to click on the edit button of custom components quickly multiple times to be able to access the edit panel.

## Video Showing Bug

https://github.com/codelab-app/platform/assets/51242349/d5fe18d9-31e5-4a82-8334-d248e22ab5cc

**Comment by assimhabeek** [comment]
@mohasarc this is duplicate of https://github.com/codelab-app/platform/issues/2676

**Comment by mohasarc** [comment]
Oh I didn't notice that, thanks!
