### ISSUE TITLE
Cannot apply font size styling to Html P

### ISSUE THREAD

**Issue by jethrocabaluna** [codelab-app/platform#2704]
## How to Reproduce

1. Add an HtmlP element
2. Try to change the font size for the html p element

## Current/Expected Behavior

Should be able to change the font size of the `<p>` element

## Video/Screenshot Showing Bug

https://github.com/codelab-app/platform/assets/27695022/06968b32-5514-4516-88fa-1dd50fbbef8d

**Comment by melhamin** [comment]
It's because `Quill` editor that we use for custom text overrides the font styles. Will be fixed with this #2290

**Comment by amrmuhamedd** [comment]
I think you should select the element like this not type directly the CSS because quill add more element more than p
https://github.com/codelab-app/platform/assets/47860740/aa474fdf-6737-4baf-9fc8-3f838b9cb3f6
