### ISSUE TITLE
Types primary sidebar and editor view

### ISSUE THREAD

**Issue by mohasarc** [codelab-app/platform#2714]
## Description

Replace the current nested tabled structure of types into a tree structure in the primary sidebar while having the type details in the editor area.

#### current

![image](https://github.com/codelab-app/platform/assets/51242349/4592772b-7eef-4bd6-befb-33358ed67ef7)

#### target

![image](https://github.com/codelab-app/platform/assets/51242349/c50f606d-589d-443a-ab3c-f46c1d878a92)

**Comment by webberwang** [comment]
As issue I see is pagination and filtering, both are easier with the table. I suppose could be implemented within the reuseable explorer

**Comment by mohasarc** [comment]
For now we can use the existing pagination service, we can have a `load more` button that loads more types similar to increasing the page size. for search we do need some UI design first, but implementation-wise we can also depend on the existing pagination service.

**Comment by mohasarc** [comment]
We can do pagination like this:

![image](https://github.com/codelab-app/platform/assets/51242349/f473aade-b5e4-4160-89f4-2334877d8b85)

**Comment by webberwang** [comment]
How does VSCode or other builders handle a tree pagination/search

**Comment by mohasarc** [comment]
Based on my research, it doesn't seem like they handle pagination; however, vscode allows for search using hotkeys (CTRL + F).

![image](https://github.com/codelab-app/platform/assets/51242349/fbefd420-ba7b-43ba-ba5d-c7f191d1919c)

I believe we can do the pagination as illustrated above; however, for the search feature, I think it is better to add a search button instead of depending on the hotkeys for a better UX. the behaviour though can be the same as vscode

**Comment by webberwang** [comment]
@mohasarc 

- right since their data is all on one page it makes sense not to have pagination. 
- I do think ui elements are better than hot keys
