### ISSUE TITLE
Atoms primary sidebar and editor view

### ISSUE THREAD

**Issue by mohasarc** [codelab-app/platform#2715]
## Description

Replace the current tabe-based Atoms page with a tree-based sidebar with an editor view for details.

#### current 

![image](https://github.com/codelab-app/platform/assets/51242349/fdf074ed-c730-40c5-9ea5-9c816fc1ec28)

#### target

![image](https://github.com/codelab-app/platform/assets/51242349/a3ff288e-fdbb-451e-bc83-b1fc34eb0d96)

**Comment by webberwang** [comment]
I'm thinking the story examples on the right should be built by our builder.

Could double as testing. We could just put some empty skeleton on the right for now, we don't need to add any stories as of now.

**Comment by vladyslav-polishchuk** [comment]
@mohasarc, Can this issue be taken into implementation? Or is there any dependency on #2714 ?

**Comment by mohasarc** [comment]
It does partially depend on [#2714](https://github.com/codelab-app/platform/issues/2714) because I've made some changes to `CuiTree` to support the search feature. The implementation can start on this, but will need to wait for #2741 to be merged to implement the search.
