### ISSUE TITLE
Cannot open Apps

### ISSUE THREAD

**Issue by melhamin** [codelab-app/platform#2724]
## How to Reproduce

1. Redirected back to `/apps` when trying to open any app.

## Video/Screenshot Showing Bug
https://github.com/codelab-app/platform/assets/48331678/6c1b485d-2988-4ab4-bab0-541cb8e050d7

**Comment by vladyslav-polishchuk** [comment]
@melhamin This seems to be related with my recent changes where I replaced ids in browser URLs with slugs. Did you try to rebuild locally? There were changes that may be not automatically applied when just running `nx serve platform`
