### ISSUE TITLE
Props are not saved

### ISSUE THREAD

**Issue by melhamin** [codelab-app/platform#2726]
## How to Reproduce

1. Props form validation fails if `UnionType` is used inside `InterfaceType` or `ArrayType`

## Video/Screenshot Showing Bug

https://github.com/codelab-app/platform/assets/48331678/97b1460e-2c3e-442b-b4a3-d49e7bf6f00e

**Comment by assimhabeek** [comment]
@melhamin  there was a change in validation steps you may check element props form for reference
