### ISSUE TITLE
Cannot open apps

### ISSUE THREAD

**Issue by melhamin** [codelab-app/platform#2745]
## How to Reproduce

1. Create an app with a number anywhere in a word in the name, for example, `App1`, `A1pp`, or `My App1`.  It works fine if there's a space in between like `App 1`, `My App 1`.

## Video/Screenshot Showing Bug

https://github.com/codelab-app/platform/assets/48331678/c0b9af70-1a6f-4807-9d23-9e115f3d9d41

**Comment by melhamin** [comment]
@vladyslav-polishchuk related to #2684 ?

**Comment by vladyslav-polishchuk** [comment]
> @vladyslav-polishchuk related to #2684 ?

@melhamin , looks like yes, it may be related. I will have a look, thanks
