### ISSUE TITLE
Vercel deployment not working for platform-api

### ISSUE THREAD

**Issue by webberwang** [codelab-app/platform#2763]
## Description

Platform api is deployed in it's own project on Vercel, the url `http://127.0.0.1:4000/api/graphql` works locally, but fails `https://api.codelab.app/api/graphql` on production.

Maybe some issue related to edge runtime that only works locally. 

https://edge-runtime.vercel.sh/packages/runtime

![Mouse_Highlight_Overlay](https://github.com/codelab-app/platform/assets/26264925/d3bafdb6-082a-4e87-9922-f225f0b327a9)

A bit hard to debug since console doesn't give much error info

**Comment by vladyslav-polishchuk** [comment]
The problem was with invalid neo4j db credentials. I manually updated Vercel env variables with valid values, but need also to sync to Terraform cloud

**Comment by vladyslav-polishchuk** [comment]
Resolved
