### ISSUE TITLE
Allow user to move the rendered elements around with the child mapper

### ISSUE THREAD

**Issue by jethrocabaluna** [codelab-app/platform#2783]
## What Feature Can Be Enhanced?
We implemented a new feature for mapping a component _n_ times based on a given prop (ideally an array) as a children.

We want users to be able to specify where the component instances will be rendered e.g.
- as last children
- as first children
- in between of the actual children of the parent

Right now, they are being rendered as last children

![image](https://github.com/codelab-app/platform/assets/27695022/4cb526e2-b12a-4861-a5d3-5eac337ea44f)

Note that the rendered component instances can't be moved around on their own, they must be moved as a whole e.g. you should not be able to move the 2nd instance only.

Also make it so that we cannot drag and drop a node into the component instances made with the child mapper

**Comment by webberwang** [comment]
Yeah does make sense to use links for ordering
