### ISSUE TITLE
Replicate the search functionality from a sample e-commerce website

### ISSUE THREAD

**Issue by jethrocabaluna** [codelab-app/platform#2784]
## Description
Try to replicate the filtering by search like in this sample [website](https://demo.vercel.store/search?sort=trending-desc)
![image](https://github.com/codelab-app/platform/assets/27695022/9d078668-6eaf-493d-b491-92565c977764)

It seems we can do the filtering on the actions, but seems theres some cache issue with the props where the rendered instances still has the old prop. So even if the data filtering works correctly, the filtered data were not rendered correctly

https://github.com/codelab-app/platform/assets/27695022/edc90365-2eea-4441-860d-71ad8d6aba52

**Comment by webberwang** [comment]
Could be related to mobx observability? It's a bit tricky when modifying data. Just throwing some possible ideas
