### ISSUE TITLE
"Pages" page is not fully functional

### ISSUE THREAD

**Issue by vladyslav-polishchuk** [codelab-app/platform#2789]
## How to Reproduce

1. Navigate to "pages" page (http://127.0.0.1:3000/apps/{username}/{app_name}/pages) 
2. See that there is no top toolbar exists

We can either add a missing toolbar for that page, or alternatively - remove the page completely, since it is not accessible from the UI, and is accessible by manually typing the URL only.

## Video/Screenshot Showing Bug

<img width="1728" alt="Screenshot 2023-07-08 at 12 35 31" src="https://github.com/codelab-app/platform/assets/74900868/2bd9ce6d-2506-4bf8-9346-c07ddcc63c3a">

**Comment by webberwang** [comment]
There was a mui toolbar I commented out when migrating, could re add it

**Comment by amrmuhamedd** [comment]
I can't Reproduce
![image](https://github.com/codelab-app/platform/assets/47860740/9247e094-d26c-4f06-8ce3-aaf719432dbb)

**Comment by webberwang** [comment]
I was able to reproduce, but the url cannot be navigated there using the UI. I was only able to navigate there by manually modifying the URL

**Comment by amrmuhamedd** [comment]
ok I see it when didn't take a default page 
here you can see
http://127.0.0.1:3000/apps/{username}/{app_name}/pages

but here no 

http://127.0.0.1:3000/apps/{username}/{app_name}/pages/pagename/builder?primarySidebarKey=pageList

**Comment by webberwang** [comment]
@amrmuhamedd What is your proposed solution?

**Comment by amrmuhamedd** [comment]
@webberwang I think we can header to this page

**Comment by amrmuhamedd** [comment]
@webberwang I think remove the page completely, since it is not accessible from the UI, and is accessible by manually typing the URL only. Is make sense
