### ISSUE TITLE
Define app pages order when displayed list of pages

### ISSUE THREAD

**Issue by vladyslav-polishchuk** [codelab-app/platform#2831]
## What Feature Can Be Enhanced?

Define some order in which pages will be displayed. Random order looks strange.

Maybe we can use system pages on top, and then regular pages sorted alphabetically under the system ones?

Currently it looks like this
<img width="395" alt="Screenshot 2023-07-22 at 12 27 51" src="https://github.com/codelab-app/platform/assets/74900868/27512156-c623-4dcc-95ed-33385ebc83d1">

The suggested list for this case could be
_app
404
500
About
Blog
Guestbook
Home

@webberwang what do you think? Does this make sense?

**Comment by webberwang** [comment]
@vladyslav-polishchuk I think

`_app` normal pages then `404` `500`

**Comment by vladyslav-polishchuk** [comment]
Currently, pages order is not as expected:

<img width="342" alt="Screenshot 2023-07-31 at 19 53 50" src="https://github.com/codelab-app/platform/assets/74900868/060984b3-3bfd-4e3f-b43e-6c97f5fc4dd0">

Also, is there a possibility to add sorting logic on some earlier stage (maybe event on request level)?
Because currently, it is visible how the order is changed. Please see video. For about a second pages displayed in random order, and only then got sorted


https://github.com/codelab-app/platform/assets/74900868/67844485-e78d-4d56-87c7-3e13c1928c10

**Comment by CreativeDev0809** [comment]
Thank for your feedback, @vladyslav-polishchuk 
You mean, it should be sorted at the request(it means it is already sorted on backend). 
Please let me know I understood right.

Many thanks.

**Comment by vladyslav-polishchuk** [comment]
I was thinking that maybe we can specify a sorting rule in our graphql request, but after some more thinking, I don't think that is possible. So most probably we would need to keep the sorting on the client side, but maybe in some other place.
Do you think it is possible to perform sorting earlier, so that pages list is not got rendered with unsorted data, as in the video above?

**Comment by CreativeDev0809** [comment]
I found the position that is not sorted in front-end.
I will fix it and rebase again.
thanks for you help. :)

**Comment by CreativeDev0809** [comment]
Fixed the issue delayed while sorting pages.
Please check and let me know if there is another problem.
Thank you for your effort.
