### ISSUE TITLE
selected overlay go out of the element when scrolling

### ISSUE THREAD

**Issue by amrmuhamedd** [codelab-app/platform#2855]
## Description of Bug
selected overlay not on element  when scrolling
## How to Reproduce

1.create many element
2.scroll to the bottom
## Video/Screenshot Showing Bug

https://github.com/codelab-app/platform/assets/47860740/6f6f1b64-e0ad-4087-973c-2771faff4cc9

**Comment by vladyslav-polishchuk** [comment]
I think the root cause may be the same as here - https://github.com/codelab-app/platform/issues/2844. Lets wait once I fix that issue and see if this is fixed as well
