### ISSUE TITLE
Fix e2e failing test due to recent UI changes

### ISSUE THREAD

**Issue by jethrocabaluna** [codelab-app/platform#2877]
## Description of Bug

Run the e2e test for these files locally and check the error, and adjust the test so that it passes. I think most of the issues is around the left sidebar changes e.g. tree list.
- `providers-page.cy.ts`
- `component.cy.ts`
- `types.cy.ts`
- `tag.cy.ts`

Try to run as well all the tests to see if there are still others that got borked. The failing e2e tests for the `builder.cy.ts` should be fixed already on https://github.com/codelab-app/platform/pull/2843

Note that e2e tests in the CI might be bogus. Sometimes it says it passed but not really. And sometimes not all tests are ran. It should be addressed in here - https://github.com/codelab-app/platform/issues/2651

**Comment by vladyslav-polishchuk** [comment]
I am currently working on e2e failures under #2863 , could take this one as well
