### ISSUE TITLE
Pages are not sorted properly

### ISSUE THREAD

**Issue by melhamin** [codelab-app/platform#2914]
## Description of Bug
- Pages are sorted after the first render.
- Sort order is broken when navigating from `Components` tab to `Pages` tab.

## How to Reproduce

1.
2.

## Video/Screenshot Showing Bug

https://github.com/codelab-app/platform/assets/48331678/880faab1-9fa2-49a0-9fba-c1157b466762

**Comment by vladyslav-polishchuk** [comment]
Did you test on the latest version of master branch? A couple of days ago the PR was merged that supposed to fix this (and I am not able to reproduce it locally). Could you double check, please?

**Comment by melhamin** [comment]
@vladyslav-polishchuk my bad, sorry. You are right it works properly. I guess I wasn't on the latest version of the master branch when noticed the issue :).

**Comment by vladyslav-polishchuk** [comment]
@melhamin , no problem at all :)
