### ISSUE TITLE
Think of approach to provide better UX for creating mobile/tablet layouts

### ISSUE THREAD

**Issue by vladyslav-polishchuk** [codelab-app/platform#2924]
## Description

Currently, to update styles for specific screen size (to show/hide content, change paddings/margins, etc) media queries can be used, like this:
```
@media (max-width: 600px) {
  display: block;
}
```

But the problem with this approach is that you can't test this in builder. Media queries are executed in context of entire window, not a specific DOM node. So for example if user app has media queries for mobile - they would not be applied in builder:

https://github.com/codelab-app/platform/assets/74900868/e19dcffd-c37f-40f0-a4b0-4a8862b3315a

Need to think of some way to provide user with ability to create layouts for PC/Tablet/Mobile with a better UX than always switching to page preview and resizing entire window to desired size.

**Comment by vladyslav-polishchuk** [comment]
Any thought and ideas are welcome

**Comment by melhamin** [comment]
I believe we should put the `Builder` inside an `iframe` element. This way we can better simulate different screen sizes and media queries should work properly.

**Comment by webberwang** [comment]
Maybe this? https://stackoverflow.com/questions/12251750/can-media-queries-resize-based-on-a-div-element-instead-of-the-screen

**Comment by vladyslav-polishchuk** [comment]
> I believe we should put the `Builder` inside an `iframe` element. This way we can better simulate different screen sizes and media queries should work properly.

This can be used as a backup plan, since I am afraid iframe approach would have a bit slower performance and maybe a bit more complex in writing e2e specs (it is usually harder to query content in frame from tests).
I will try an approach with container media queries first, this looks pretty promising
