### ISSUE TITLE
Experiment with Custom Static Site Rendering Without Shipping Next.js and React to the Client

### ISSUE THREAD

**Issue by nettohadi** [codelab-app/platform#2930]
### Which Feature Can Be Enhanced?
We are exploring the concept of custom static site rendering and generation without delivering Next.js and React to the client. This means serving only plain HTML and CSS to the client.

### What Are the Benefits?

- **Reduced Payload Size**: Our current payload size is almost double due to the metadata embedded within the HTML page.
  
- **Decreased Blocking Time**: React blocks the thread for hydration on the client side using the metadata in the page. Without React, blocking time is significantly reduced.
  
- **Minimal JS Bundle**: Without Next.js or React, our JS bundle could be reduced to a negligible size.

### What Are the Trade-offs?

- **No State Management**: Naturally, as we won't be deploying React.
  
- **Limited Interactivity**: Without React, much of our site's interactivity will be lost. However, basic interactivity can still be achieved by creating a separate JS file.

### Why Pursue This Approach?

Not every application requires heavy state management or extensive interactivity. We believe users should have the option to choose between a fully dynamic, state-intensive application or a simpler landing page. By offering statically rendered options, we can provide the best possible performance for those who prefer it.

### Why Explore Beyond Existing Methods Like `getServerSideProps` or `getStaticProps`?

Both `getServerSideProps` and `getStaticProps` have their own merits, but they also come with certain limitations that affect performance:

- **Embedded Metadata with `getServerSideProps`**: This approach embeds metadata necessary for hydration directly into the HTML. As a consequence, the size of the page is increased.
  
- **Embedded Metadata in Development with `getStaticProps`**: While `getStaticProps` generally avoids embedding hydration metadata in the production build, this metadata still gets embedded during development, making it less streamlined than it could be.

- **Mandatory Client-Side Hydration**: Regardless of the method used, both approaches mandate client-side hydration. This means shipping both Next.js and React to the browser, which adds to the initial payload.

Given these points, while `getStaticProps` might be a step in the right direction, we believe there's room for optimization. By experimenting with new approaches, our goal is to achieve the best possible performance for our web applications.

**Comment by webberwang** [comment]
SSG: https://codedbydolapo.hashnode.dev/server-side-rendering-and-static-site-generation-with-nextjs

Why Next.js is slow: https://github.com/vercel/next.js/issues/44766#issuecomment-1380341140

Refresher on hydration: https://blog.saeloun.com/2021/12/16/hydration/

**Comment by webberwang** [comment]
@nettohadi Let's pause this since it's only a partial solution, but it's good to know our options
