### ISSUE TITLE
Introduce CSS breakpoints in builder

### ISSUE THREAD

**Issue by vladyslav-polishchuk** [codelab-app/platform#2942]
## Description

Please see comments on this PR - https://github.com/codelab-app/platform/pull/2936

**Comment by vladyslav-polishchuk** [comment]
Currently I try to follow the approach @nettohadi suggested [here](https://github.com/codelab-app/platform/pull/2936#issuecomment-1693012451). When specific breakpoint is selected - styles are saved for that breakpoint using media query for production, or container query for development.
Looks promising, no show-stoppers so far. 
Please let me know if I need to switch direction

Here is an intermediate result:

https://github.com/codelab-app/platform/pull/2936#issuecomment-1693012451

**Comment by vladyslav-polishchuk** [comment]
To make this possible, I replaced `guiCss` and `customCss` props on element with a single `style` property that are going to store all information about styling in the following form

```
style: "{\"desktop\":{\"cssString\":\"margin-top: 50px;\\ncolor: black;\"},\"tablet\":{\"cssString\":\"color: green;\"},\"mobile-landscape\":{\"cssString\":\"color: purple;\"},\"mobile-portrait\":{\"cssString\":\"color: orange;\"}}"
```

**Comment by webberwang** [comment]
working quite nicely

**Comment by webberwang** [comment]
working quite nicely, I'm guessing the styles apply directly to the breakpoint. But in practice, maybe we want multiple breakpoints to use the same rule, how does the precedence of the rules work? its mobile first?

**Case 1**

- Apply the rule to the current breakpoint only.

**Case 2**

- Mobile first

some scenarios, say I want to apply a style of yellow text 

O - apply
X - don't apply

 mobile | tablet | desktop 
 -----------------------
1.    O         O          O
2.    X         O         O


A mobile first approach means adding the CSS to mobile view will apply to all, then we'll need to re-override at the bigger breakpoints

In 1. we will add rule to mobile, in 2. we will add rule to tablet

***UI***

For case 1, I could imagine the CSS to be visible but disabled for edit in tablet/desktop view, since it is created in mobile view. 

But we could add a new rule in tablet to override the first rule, this new rule will be visible in desktop view (while disabled as well)

Maybe disabled could be confusing, might imply that it isn't applied. Just some brainstorm

---

There could be other behavior, but mobile first's implementation and use case seem best value for the amount of work.

**Comment by vladyslav-polishchuk** [comment]
> working quite nicely, I'm guessing the styles apply directly to the breakpoint. But in practice, maybe we want multiple breakpoints to use the same rule, how does the precedence of the rules work? is it mobile first?
> 
> **Case 1**
> 
> * Apply the rule to the current breakpoint only.
> 
> **Case 2**
> 
> * Mobile first
> 
> some scenarios, say I want to apply a style of yellow text
> 
> O - apply X - don't apply
> 
> ## mobile | tablet | desktop
> 1. O         O          X
> 2. X         O         O
> 
> A mobile first approach means adding the CSS to mobile view will apply to all, then we'll need to override at the bigger breakpoints
> 
> In 1. we will add rule to mobile, and add a new rule at desktop.
> 
> In 2. we will add rule to tablet
> 
> _**UI**_
> 
> For case 1, I could imagine the CSS to be visible but disabled for edit in tablet/desktop view, since it is created in mobile view.
> 
> But we could add a new rule in tablet to override the first rule, this new rule will be visible in desktop view (while disabled as well)
> 
> Maybe disabled could be confusing, might imply that it isn't applied (could just make it not-editable). Just some brainstorm
> 
> There could be other behavior, but mobile first's implementation and use case seem best value for the amount of work.

Currently it is desktop-first, so all the styles that are set for desktop - will apply to smaller screens, and if the same style is set for tablet - it will override desktop style and apply for all smaller screens, and so on.
This was the first implementation, but now I am thinking that you are right, probably need to make mobile-first instead and reverse the logic.

Sure, I will think some more on UI details

**Comment by nettohadi** [comment]
In Webflow or other website builders, styles set for a higher breakpoint apply to the lower breakpoints unless overridden. For instance, if we set the background color to red on the desktop view, that same style will carry over to both tablet and mobile views. However, if we change the background color to blue in the tablet view, this new color will also apply to the mobile view, but the desktop remains red. Lastly, any style changes made specifically in the mobile view won't affect the tablet or desktop.

So far, I've never seen or used a website builder that promotes a mobile-first approach. **Of course**, there is no right or wrong approach here. I'm just saying if we decide to promote the mobile-first approach by default, we will present users with an unfamiliar approach that might have a learning curve.

However, having a mobile-first approach option could set Codelab apart as innovative and forward-thinking, especially in a world that's increasingly mobile-centric.

**So here is what I recommend:** We promote the desktop-first approach by default and offer an option for those who want to use the mobile-first approach. The key would be to provide intuitive tools and guidance to make the transition smoother for users who are accustomed to desktop-first.

What do you guys think, @webberwang @vladyslav-polishchuk?

Desktop-first in Webflow: https://www.loom.com/share/bdabd530066040769fdc4a298d4f4145
Desktop-first in Makeswift: https://www.loom.com/share/e1a1b162f307462b9b7522d869e6b48e

**Comment by webberwang** [comment]
Well the initial philosophy is to follow coding philosophy more closely https://tailwindcss.com/docs/responsive-design#working-mobile-first, but if users want so otherwise we could always consider changing down the line

**Comment by nettohadi** [comment]
> Well the initial philosophy is to follow coding philosophy more closely https://tailwindcss.com/docs/responsive-design#working-mobile-first, but if users want so otherwise we could always consider changing down the line

Agree.

**Comment by vladyslav-polishchuk** [comment]
@webberwang , @nettohadi, so, we are going to provide mobile-first styling by default, with ability to switch to desktop-first if user wants so (seems to be easy to implement switching between approaches at the moment), right?

**Comment by webberwang** [comment]
> @webberwang , @nettohadi, so, we are going to provide mobile-first styling by default, with ability to switch to desktop-first if user wants so (seems to be easy to implement switching between approaches at the moment), right?

Do without the switching for now, just mobile-first

**Comment by webberwang** [comment]
looks great! having 2 separate css boxes make it more clear
