### ISSUE TITLE
Build issue on master branch

### ISSUE THREAD

**Issue by assimhabeek** [codelab-app/platform#2951]
## How to Reproduce
![image](https://github.com/codelab-app/platform/assets/33001357/7877efba-c2ad-4f7b-b05c-9853f29fbd34)

**Comment by webberwang** [comment]
![Mouse_Highlight_Overlay](https://github.com/codelab-app/platform/assets/26264925/a3cc0061-3211-4435-a1d7-8a13bfafa12d)

temp fix here

**Comment by assimhabeek** [comment]
The issue is that `store.api` shouldn't be nullable or else  it will effects other things. I made a PR with this temp fix but I will resolve the problem for its roots
