### ISSUE TITLE
`theme` prop of the AntDesignMenu is not working

### ISSUE THREAD

**Issue by jethrocabaluna** [codelab-app/platform#2956]
## Description of Bug
Somehow the `theme` prop of the AntDesignMenu is not working anymore. It seems it is not getting passed into the actual component. This was still working last week though, i am not sure yet whats the cause of the issue.

Also not sure if there are other atoms that got affected too.

## How to Reproduce

1. Create an AntDesignMenu element
2. Add some items
3. Select "dark" on the `theme` prop

## Video/Screenshot Showing Bug
<img width="1878" alt="Screenshot 2023-08-29 at 4 49 19 PM" src="https://github.com/codelab-app/platform/assets/27695022/33d82efb-2d53-4329-9b37-aefc7519874e">

**Comment by vladyslav-polishchuk** [comment]
via Hubstaff
User: Vladyslav Polishchuk

Project: platform - https://app.hubstaff.com/projects/2961404
Date Range: 05/02/24 - 05/02/24
Work session total: 1:56:10
Billable: Yes

Grand total: 1:56:10
