### ISSUE TITLE
Child mapper component names are not unique

### ISSUE THREAD

**Issue by melhamin** [codelab-app/platform#2972]
## Description of Bug
The components created by the child mapper do not have unique names. 
The child mapper e2e should have caught this bug but seems that due to recent merges (ignoring ci) something has broken it.

## How to Reproduce

1.
2.

## Video/Screenshot Showing Bug

https://github.com/codelab-app/platform/assets/48331678/be342122-d513-41ae-a185-83dc647e1fc0

**Comment by vladyslav-polishchuk** [comment]
via Hubstaff
User: Vladyslav Polishchuk

Project: platform - https://app.hubstaff.com/projects/2961404
Date Range: 04/08/24 - 04/12/24
Work session total: 5:05:29
Billable: Yes

Grand total: 5:05:29
