### ISSUE TITLE
Impossible to set inner text on Link atom

### ISSUE THREAD

**Issue by vladyslav-polishchuk** [codelab-app/platform#2985]
## How to Reproduce

1. Create a NextLink atom on the page
2. Try to set a text label for the link

The user is being redirected to the link target page

## Video/Screenshot Showing Bug

https://github.com/codelab-app/platform/assets/74900868/d1c4486a-00e3-40d4-9c13-ff16f152157b

**Comment by melhamin** [comment]
This is due to the inline text editor. When clicking on the element to type, the default action is to navigate. Should find a way to `preventDefault` in builder.

**Comment by nettohadi** [comment]
I would suggest not running any actions (or preventing navigation by a link) in builder mode since builder mode is for design. Instead, these actions should be executed in preview and production modes. Webflow follows the same approach.

**Comment by webberwang** [comment]
Related https://github.com/codelab-app/platform/pull/2988#issuecomment-1714186943
