### ISSUE TITLE
Simplify route change hooks in the preview mode

### ISSUE THREAD

**Issue by jethrocabaluna** [codelab-app/platform#3011]
## What Feature Can Be Enhanced?
We have this logic in the [preview mode](https://github.com/codelab-app/platform/blob/36f2515683549d5b611106ec5701fb6c47c46f63/apps/platform/pages/apps/%5BuserName%5D/%5BappSlug%5D/pages/%5BpageSlug%5D/index.tsx) where we use three effect hooks. We could simplify this, and should add notes on how or why it is implemented this way.

Also make sure that there are no dupe listeners being added into the `routeChangeStart` event. You can check this by adding console log on the event handler, it should only trigger once per route change

We should also remove the routing hooks logic in the builder file, since the NextLink behaviour should be disabled in the builder, and only works on the preview mode, as mentioned in here - https://github.com/codelab-app/platform/pull/2988#issuecomment-1715393437

![image](https://github.com/codelab-app/platform/assets/27695022/dc53505a-e464-4122-ad3d-6769a29f88c9)

**Comment by webberwang** [comment]
Add Cypress spec to test this, something like this to test it above

![menu_cy_ts_—_platform](https://github.com/codelab-app/platform/assets/26264925/f9dc8a8e-8f08-4ce5-9151-5f4e6439a7e7)
