### ISSUE TITLE
Allow to switch between mobile-first and desktop-first

### ISSUE THREAD

**Issue by vladyslav-polishchuk** [codelab-app/platform#3015]
## Description

Currently, styling was implemented to follow a mobile-first approach. This means that:
- The default breakpoint selected in the builder is "mobile" whenever the user opens a page or component:
<img width="1728" alt="Screenshot 2023-09-14 at 09 32 45" src="https://github.com/codelab-app/platform/assets/74900868/7f1ccdf9-80dd-4f94-bfdf-5aba69008bb9">
- Styles defined on smaller screens are inherited by larger breakpoints

However, not all users may want to follow this approach. So as a further enhancement, I suggest adding a checkbox/dropdown on app form to toggle between mobile and desktop-first approaches:
<img width="649" alt="Screenshot 2023-09-14 at 09 43 44" src="https://github.com/codelab-app/platform/assets/74900868/79b93ad4-788f-45a6-94a1-f0d0b4d6b6d4">

Any further suggestions are welcome

**Comment by webberwang** [comment]
Let's stick with mobile first, don't want to complicate the code/requirements too much

**Comment by vladyslav-polishchuk** [comment]
Sure, I will cancel issue then
