### ISSUE TITLE
Refactor uniform field components

### ISSUE THREAD

**Issue by webberwang** [codelab-app/platform#3028]
## Description

- [x] I'm seeing too much filter/map/reduce logic in React components. For example https://github.com/codelab-app/platform/blob/b4056d1fb72f84c7a10f3747d737667c37bdff9e/libs/frontend/domain/type/src/interface-form/fields/select-element/SelectElement.tsx#L23

We can move many methods to mobx, and change the props of the form field to something that only has the required props

- [x] Another example https://github.com/codelab-app/platform/blob/b4056d1fb72f84c7a10f3747d737667c37bdff9e/libs/frontend/domain/type/src/interface-form/fields/select-component/SelectComponent.tsx#L14. These form components should be stateless.

- [x] Also https://github.com/codelab-app/platform/blob/b4056d1fb72f84c7a10f3747d737667c37bdff9e/libs/frontend/domain/type/src/interface-form/fields/select-atom/SelectAtom.tsx#L22

Here we have hooks and memo, but I think if we move logic to mobx, we wouldn't need those anymore since mobx handles reactivity.

---

We want to centralize any type of logic to our mobx services, and form select logic is one of them as well.

---

- [x] Look at how uniform deals with `oneOf` union type schema. Could be useful since we have many use cases like this. Would be great to have it working out the box

**Comment by melhamin** [comment]
@webberwang we already have `SelectUnionTypeValue` which uses `oneOf`. isn't that working right now?

**Comment by webberwang** [comment]
> @webberwang we already have `SelectUnionTypeValue` which uses `oneOf`. isn't that working right now?

Right can ignore thanks

**Comment by webberwang** [comment]
> SelectUnionTypeValue

It does but we have to create our own SelectField, it's not a huge deal though, just some research
