### ISSUE TITLE
Determine the best approach for integrating Tailwind CSS into the builder

### ISSUE THREAD

**Issue by nettohadi** [codelab-app/platform#3043]
## Description
We're planning to allow users to utilize Tailwind CSS within the builder, offering more styling options for their apps, especially for those who already use it in their day-to-day work.

However, we've quickly recognized the complexity of this task. Tailwind, especially with its new JIT compiler, requires a runner or bundling tool to operate effectively. The JIT compiler generates Tailwind classes on-the-fly, offering improved performance by not loading all Tailwind classes by default. We'd prefer not to run a bundling tool within the builder. While the straightforward solution is to load all the classes, that's not ideal for us. We need a way to utilize the JIT compiler without relying on a bundling tool.

**Comment by nettohadi** [comment]
### Tailwind JIT compiler via CDN
One of our first option is to use [Tailwind JIT compiler via CDN](https://beyondco.de/blog/tailwind-jit-compiler-via-cdn). It doesn't require any bundling tool and provides most of Tailwind features with a few exceptions and even supports generating classes based on [arbitrary values](https://v2.tailwindcss.com/docs/just-in-time-mode#arbitrary-value-support). 

It uses [MutationOberver](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) to watch any changes made to class attribute. that means that you can add classes via the browser developer tools and the CSS gets an update dynamically.

### Implementation in the builder
Using the Tailwind JIT compiler via CDN in our builder is straightforward. In fact, we hardly need to do anything. Simply rendering the React component with Tailwind classes allows the JIT compiler to detect those classes and generate the CSS dynamically.

### Performance issue
Regrettably, this ease of use has its drawbacks. As I've mentioned earlier, the Tailwind JIT compiler via CDN leverages the MutationObserver to monitor changes. It observes the [entire document](https://github.com/beyondcode/tailwindcss-jit-cdn/blob/main/src/main.js#L12), which can significantly impact performance. Given that we use styled components and often mutate classes or attributes, these changes can trigger the compiler callback with high frequency.

**Comment by webberwang** [comment]
Could we not use JIT during builder mode, but strip classes for production?

**Comment by nettohadi** [comment]
> Could we not use JIT during builder mode, but strip classes for production?

You mean load all the classes during builder mode (thus removing the need for JIT) and  purge unused classes in production?

**Comment by nettohadi** [comment]
### Twind

[Twind](https://twind.dev/handbook/introduction.html#features) is a compact compiler (around 13kB) that transforms Tailwind utility classes into CSS at runtime. It eliminates the need for any bundling tool, making it an ideal fit for our use case. It's similar to styled components, but instead of producing random classes, it generates Tailwind-specific classes.

### Implementation in the builder

Using Twind is very similar to how we use Styled Components as both utilize string literal. The difference is Twind takes Tailwind classes and generate the css while Styles Components accept css. To generate css for Tailwind utility classes at runtime, we only need to call `tw` and pass the list of classes separated by spaces. We can use `tw` within the `element-wrapper` and get the list of classes from the `className` prop.

![how-twind-works](https://github.com/codelab-app/platform/assets/32300655/080649e4-06a7-476a-acc2-fee44a4b28ce)

### Performance impact

Twind fits our use case perfectly, but what about its potential impact on performance? After extensively testing it during the UI development for adding Tailwind classes, I can confidently say that there's no noticeable negative effect on the builder's performance. Twind appears to be highly optimized in this regard, as further evidenced by [benchmarks](https://twind.dev/handbook/introduction.html#benchmarks) on its official website.

### Production optimization

Twind supports static extraction a.k.a. Server Side Rendering (SSR) out of the box.

```javascript
import { setup } from 'twind'
import { virtualSheet, getStyleTag } from 'twind/sheets'

const sheet = virtualSheet()

setup({ ...sharedOptions, sheet })

function ssr() {
  // 1. Reset the sheet for a new rendering
  sheet.reset()

  // 2. Render the app
  const body = renderTheApp()

  // 3. Create the style tag with all generated CSS rules
  const styleTag = getStyleTag(sheet)

  // 4. Generate the response html
  return `<!DOCTYPE html>
    <html lang="en">
      <head>${styleTag}</head>
      <body>${body}</body>
    </html>
  `
}
```
