### ISSUE TITLE
Refactor dropPosition to use Ref<IElementModel>

### ISSUE THREAD

**Issue by webberwang** [codelab-app/platform#3049]
## Description

- Refactor dropPosition to use Ref<IElementModel>

we're using indices for children to tell us where to drop to, but seems better to pass Ref and perform insertAfterElement or something

- Take in Ref<IElementModel> as param instead of id for all element related services

**Comment by nettohadi** [comment]
Hi @webberwang, could you please provide some details regarding this issue??

**Comment by webberwang** [comment]
@nettohadi haven't quite assigned yet, but I saw this going through the codebase. we're using indices for children to tell us where to drop to, but seems better to pass Ref<IElementModel> and perform insertAfterElement or something

**Comment by webberwang** [comment]
@nettohadi could be `ElementModel` type as well, might be better without the ref, feel free to try and see
