### ISSUE TITLE
Fix websites projects

### ISSUE THREAD

**Issue by assimhabeek** [codelab-app/platform#3063]
## What Feature Can Be Enhanced?

Get websites project working following refactor done by #3023

**Comment by webberwang** [comment]
@vladyslav-polishchuk Add a cypress spec for a simple production site app.

Just build 2 pages and visit each page and assert some text content on the page

**Comment by vladyslav-polishchuk** [comment]
> @vladyslav-polishchuk Add a cypress spec for a simple production site app.
> 
> Just build 2 pages and visit each page and assert some text content on the page
> 
> This will be basically like `in-app-routing.cy.ts`

@webberwang, do you mean manually creating an application in production (admin.codelab.app), creating a couple of pages, assigning a domain and then in spec only try to access the resulting website (over custom user domain)?

**Comment by vladyslav-polishchuk** [comment]
@webberwang, do you think it makes sense to assign some demo domains to every app that are created by users?
For example, whenever user creates an app - it gets `app-id.websites.codelab.app` domain, and the app becomes immediately available by that URL. And if user wants to add custom one - this could be a part of some paid plan.
Just an idea. Seems like could be easily implemented

**Comment by webberwang** [comment]
> @webberwang, do you think it makes sense to assign some demo domains to every app that is created by users? For example, whenever user creates an app - it gets `app-id.websites.codelab.app` domain, and the app becomes immediately available by that URL. And if user wants to add custom one - this could be a part of some paid plan. Just an idea. Seems like could be easily implemented

Yeah definitely could you create a task for the backlog?
