### ISSUE TITLE
Error when selecting a tailwind class

### ISSUE THREAD

**Issue by melhamin** [codelab-app/platform#3068]
## Description of Bug
The error occurs even when any item is not selected, just hovering over any item causes the error.
## How to Reproduce

1. Checkout `dev` branch
2.

## Video/Screenshot Showing Bug

https://github.com/codelab-app/platform/assets/48331678/3b223bdd-bfcb-435f-817b-913dd33a151b

**Comment by nettohadi** [comment]
@webberwang @melhamin, just need to uncomment `install(config)` in line 14 to fix this bug.
![Screen Shot 2023-10-12 at 12 41 43](https://github.com/codelab-app/platform/assets/32300655/ce4535d8-562e-4976-a2ef-b3ab8534b0d3)

**Comment by nettohadi** [comment]
I will create a mini PR.
