### ISSUE TITLE
Types are not loaded

### ISSUE THREAD

**Issue by melhamin** [codelab-app/platform#3078]
## Description of Bug
Not all types used in a page are loaded. Currently, the following types are loaded when loading an app.
<img width="1726" alt="Screenshot 2023-10-12 at 17 09 15" src="https://github.com/codelab-app/platform/assets/48331678/a16ce893-70cf-4360-9c83-f702423a26a7">

This is missing some of the system types i.e. `ActionType` also the types of the api fields of elements.

### Proposed solution
As per talks with @webber, it would be ideal to have a custom resolver that would load all of the types. Because we want to load an app and its elements, and types, ... in a single query. 
## How to Reproduce

1. 
2.

**Comment by webberwang** [comment]
@melhamin is this related to refactoring `loadAllTypesForElements`?

**Comment by melhamin** [comment]
> @melhamin is this related to refactoring `loadAllTypesForElements`?

@webberwang yes.
