### ISSUE TITLE
Atom id is shown instead of name in dropdown

### ISSUE THREAD

**Issue by vladyslav-polishchuk** [codelab-app/platform#3086]
## How to Reproduce

1. Create a couple of atoms on a page
2. See the "Atom" dropdown in "Renderer" tab

## Video/Screenshot Showing Bug

https://github.com/codelab-app/platform/assets/74900868/6e327da6-5246-430e-adaf-203285ce7bb4

**Comment by webberwang** [comment]
@vladyslav-polishchuk this seems fixed in #3087, closing for now. Let me know if need to be re-opened

**Comment by vladyslav-polishchuk** [comment]
> @vladyslav-polishchuk this seems fixed in #3087, closing for now. Let me know if need to be re-opened

Correct, this is fixed
