### ISSUE TITLE
Tailwind warning logs

### ISSUE THREAD

**Issue by melhamin** [codelab-app/platform#3100]
## Description of Bug
There are warning logs in the console when `tailwind` classes is enabled. 
## How to Reproduce

1.
2.

## Video/Screenshot Showing Bug
<img width="1725" alt="Screenshot 2023-10-24 at 00 30 55" src="https://github.com/codelab-app/platform/assets/48331678/7b39c684-4561-4f28-aaa9-3d3f9bbe18d1">

**Comment by nettohadi** [comment]
Apology, I didn't realize this issue was already assigned to you, @melhamin.

**Comment by melhamin** [comment]
@nettohadi no worries.
