### ISSUE TITLE
Drag & drop functionality

### ISSUE THREAD

**Issue by webberwang** [codelab-app/platform#3122]
## Description

Our previous dnd was deleted here https://github.com/codelab-app/platform/pull/3055/files#diff-0b00bad046ac925a5be0f510cf8c5815121bf00e2a795933a8de19256cbbc9f9 perhaps unintentionally

A new PR was WIP here https://github.com/codelab-app/platform/pull/3095 and it uses a different strategy. I'm not too sure which way is best, maybe you could take a look

**Comment by jethrocabaluna** [comment]
Oh I remember removing those because I thought we are doing a new implementation. See related thread here https://codelab-app.slack.com/archives/C01TALGNKMZ/p1696586290576399

**Comment by mohasarc** [comment]
oh I see, thanks!
