### ISSUE TITLE
Vercel serverside timeout

### ISSUE THREAD

**Issue by webberwang** [codelab-app/platform#3143]
## Description

- Noticed only times out when we do `getServerSideProps`, even for empty block
- Not related to auth0
- https://github.com/vercel/next.js/discussions/47237
- Possibly related to Ant Design icon
- Maybe on serverside, the bundle size is too large if we import icon directly
- Added eslint rule to test it out

---

Seems like issue happens when we have to do SSR rendering for _app.tsx, looks to be the function for creating store, it's a lot of mobx code & is likely slower on Vercel

we can add opentelemetry to track those functions to see how long they take to run, otherwise we are sitting in the dark https://opentelemetry.io/docs/demo/services/frontend/

That url has a next.js demo

After exploring the demo, it seems to wrap the api handlers, might not be suited for the frontend

https://nextjs.org/docs/app/building-your-application/optimizing/open-telemetry

---

Ended up using the official vercel integration, which integrates with new relic for the dashboard

![_app_tsx_—_platform](https://github.com/codelab-app/platform/assets/26264925/f00f5b41-a13f-4a76-b772-e4260675b421)

![platform___New_Relic_One_and_instrumentation_ts_—_platform](https://github.com/codelab-app/platform/assets/26264925/3a843359-b490-411f-9b4a-ef055f2e010e)

As you can see, the `initializeStore` itself takes about 21 seconds.

Couldn’t get the traces showing up on new relic, this seems overkill we don’t really need it 

---

Found this thread

- https://github.com/vercel/next.js/discussions/12447

A user thought it was cold start, but pinpointed to something else `mobx-react`

- https://github.com/vercel/next.js/discussions/12447#discussioncomment-7095212
- https://github.com/vercel/next.js/issues/53624#issuecomment-1713578575

This doesn't seem to be the issue
---

Another idea is to use edge runtime, but when switching over, I faced an ESM issue. The edge runtime imports a lib using ESM, since it is internal code, we don't have access to it. So started migrating our project to use ESM.

Actually we can use https://github.com/martpie/next-transpile-modules/releases/tag/the-end so don't need to migrate everything over

**Comment by vladyslav-polishchuk** [comment]
The `platform` and `platform-api` projects were migrated to DigitalOcean App platform. The servers are always up and running so there is no more issue with cold start. Lighthouse reports pretty good performance results for production hosted even on the smallest instances:

<img width="1728" alt="Screenshot 2023-12-13 at 20 28 28" src="https://github.com/codelab-app/platform/assets/74900868/f15e561b-a6a4-4d7c-bc5a-8f20d43785b6">

For now no critical performance issues exist, and no timeout errors anymore. Closing the issue as completed
