### ISSUE TITLE
New element is not rendered

### ISSUE THREAD

**Issue by melhamin** [codelab-app/platform#3157]
## Description of Bug
New elements are not rendered until the page is refreshed.

## How to Reproduce

1.
2.

## Video/Screenshot Showing Bug

https://github.com/codelab-app/platform/assets/48331678/97b277d5-60e6-4bd0-9fb7-398479590660

**Comment by jethrocabaluna** [comment]
Fix is included in the PR https://github.com/codelab-app/platform/pull/3185

**Comment by vladyslav-polishchuk** [comment]
Already completed in https://github.com/codelab-app/platform/pull/3200
