### ISSUE TITLE
Crashing when opening a component in the component builder

### ISSUE THREAD

**Issue by jethrocabaluna** [codelab-app/platform#3191]
## Description of Bug
When trying to edit a component, the app crashes about a ResizeObserver error. But after a reload, the component builder opens but there are no resize viewport options

## How to Reproduce

1. Go to components builder
2. Open any component

## Video/Screenshot Showing Bug

https://github.com/codelab-app/platform/assets/27695022/f018e345-a8b5-443a-9ed0-c92c06a47e82

**Comment by melhamin** [comment]
@jethrocabaluna this seems to be fixed. Can you also test?

**Comment by melhamin** [comment]
Hi @jethrocabaluna, you are right, it still happens. I tested it when there were no elements on the current page, which didn't throw an error. But it happens in some other cases.


https://github.com/codelab-app/platform/assets/48331678/1f30b001-7f7b-4e71-936e-be2fe4663bdb
