### ISSUE TITLE
Chatbot custom component using openai API

### ISSUE THREAD

**Issue by jethrocabaluna** [codelab-app/platform#3248]
## Description

~~The idea is for users to be able to use some gpt models or similar in their apps.~~
- ~how can they fine-tune a gpt model via our platform so that they can use it in their app~
  - ~or maybe they can just fine-tune a model in [openai UI](https://platform.openai.com/finetune)~
- ~how will apps use openai api with their fine-tuned model~
- ~how can we make it easily available for our users to integrate via UI~

~~For now, we could use the e-commerce sample app and integrate a gpt model for services like recommendations or chatbot, etc~~

---

Instead of building, let's clone Github projects. Here are some options

- https://github.com/hiyouga/LLaMA-Factory

---

As a start, we will try to create a chatbot component that uses openai API for chat completion and will try to use it on pages.

**Comment by webberwang** [comment]
After currently refactoring the Cypress specs & hearing you mention having the Cypress specs all test the same app, we could build this next AI application through a test driven approach.

We'll refactor all the Cypress specs to be testing features in the AI, such as store/resources/actions/builder/preview/components etc.

Having real world data makes the specs much more understandable as well, as opposed to having names such as `key1`, `key2`.

This would be the first of many apps that are Cypress tested.
