### ISSUE TITLE
Cannot create app

### ISSUE THREAD

**Issue by melhamin** [codelab-app/platform#3264]
## How to Reproduce

1.
2.

## Video/Screenshot Showing Bug

https://github.com/codelab-app/platform/assets/48331678/12b89541-6886-46a5-a6b5-d40c4d1ae8e7

**Comment by vladyslav-polishchuk** [comment]
This could be related to my recent PR with authentication. Let me have a look

**Comment by melhamin** [comment]
@vladyslav-polishchuk I have pulled the latest master version and re-seeded the db still getting the issue. There seems to be a problem with authentication since the `GetAppList` request fails too. 

Here's the video, includes the stack trace.

https://github.com/codelab-app/platform/assets/48331678/301158b8-7789-4d57-94ec-3ebc2d3318e1

**Comment by melhamin** [comment]
Getting this error when going to the Atoms page. I think authentication error causes the atoms to not be loaded hence the fails to get the defaultRenderType.

<img width="1728" alt="Screenshot 2024-03-04 at 1 54 06 PM" src="https://github.com/codelab-app/platform/assets/48331678/f7826635-26ea-43e3-8d1c-11957b796b3a">

**Comment by vladyslav-polishchuk** [comment]
@melhamin, could you also try logout and then login again?
Checked the production as well, there is no such error. In case re-login does not help either - could you share your local .env file, to make sure nothing is missing?

**Comment by melhamin** [comment]
That's strange. I tried re-login as well.

**Comment by webberwang** [comment]
@melhamin sometimes the artifact remains in the neo4j db, so you may need to remove the docker volume and re-create it
