### ISSUE TITLE
Explorerer tree flickers

### ISSUE THREAD

**Issue by webberwang** [codelab-app/platform#3275]
## Description of Bug

The tree shows all open first, then it folds.

It should ideally remember last state, but we still need some initial state.

What should this initial state be (all closed? all open?)

https://github.com/codelab-app/platform/assets/26264925/071adeb8-0eb2-454b-835e-29e81281884b

**Comment by vladyslav-polishchuk** [comment]
via Hubstaff
User: Vladyslav Polishchuk

Project: platform - https://app.hubstaff.com/projects/2961404
Date Range: 04/13/24 - 04/26/24
Work session total: 16:14:54
Billable: Yes

Grand total: 16:14:54
