### ISSUE TITLE
Provider state is not passed into Component state-sharing.cy.ts

### ISSUE THREAD

**Issue by webberwang** [codelab-app/platform#3277]
## How to Reproduce

1. Show provider state
2. Show component state
3. Show the page preview's data (is showing default component state, not provider)

## Video/Screenshot Showing Bug

https://github.com/codelab-app/platform/assets/26264925/bae3a350-8522-4adb-9227-8201614a7356

**Comment by webberwang** [comment]
We don't pass provider state into components

**Comment by Wuffle1125** [comment]
We can use Octokit module.
