### ISSUE TITLE
Write unit specs for antdTree

### ISSUE THREAD

**Issue by assimhabeek** [codelab-app/platform#3321]
## What Feature Can Be Enhanced?
Element tree view has many cases that needs to be tested:
- Show element which belongs to the main tree.
- When element is a component instance don't show component as a child. (This goes against the real shape of tree)
- Show instance element children as direct children (even thought they will be wrapped by component on render. or not rendered at all)
- Show child mapper children     
- Set correct rootKey

Many issues are related to this is one :

#3319
#3308
#3272

**Comment by webberwang** [comment]
Nice this will be quite useful

**Comment by assimhabeek** [comment]
via Hubstaff
User: assim

Project: platform - https://app.hubstaff.com/projects/2961404
Date Range: 04/09/24 - 04/13/24
Work session total: 6:34:40
Billable: Yes

Grand total: 6:34:40
