### ISSUE TITLE
Replace allowRichTextInjection with children: RichTextEditor

### ISSUE THREAD

**Issue by webberwang** [codelab-app/platform#3338]
## Description

Create a new type for RichTextEditor, and assign to all atom's children property. This will show the WYSIWYG editor in the PropsForm

Would clean up this conditional logic

![runtime-element_model_ts_—_platform](https://github.com/codelab-app/platform/assets/26264925/dd3e7a13-9664-4243-b31b-3e11255eea12)

And push the logic to the `atom-render-pipe`

We'll need to inject `runtimeElement` to all atoms via the atomFactory since  `TextEditorWrapper` requires it.

`TextEditorWrapper` will become the atom exposed to the user, since I think the `TextEditor` itself is not really useable on its own.

Can rename `TextEditorWrapper -> TextEditor` and `TextEditor -> TextEditorInternal`

**Comment by assimhabeek** [comment]
Element may have children in one of the following ways :
- Creating a new element and attaching it to element tree (**High Priority**) it will override any other children
- Adding via children prop, children prop could have two types `RichTextType` or `ReactNodeType`. The reason we need `ReactNodeType` is the case of injecting other element trees by expressions like `{{componentProps.children}}`.  expression evaluation will return a react object so we will have a string containing React object which will be parsed with `DOMParser` producing a wrong output.

Another thing to notice is about expressions that returns React objects is that must have the following format `{{path.to.node}}` something like `some text {{path.to.node}}` will not work properly

**Comment by assimhabeek** [comment]
via Hubstaff
User: assim

Project: platform - https://app.hubstaff.com/projects/2961404
Date Range: 04/15/24 - 04/28/24
Work session total: 34:29:24
Billable: Yes

Grand total: 34:29:24
