### ISSUE TITLE
Child mapper should only work for atom type

### ISSUE THREAD

**Issue by webberwang** [codelab-app/platform#3339]
## Description

The element should not be Component type if we're using child mapper

![_app___Builder___Codelab](https://github.com/codelab-app/platform/assets/26264925/d54fb992-9f61-41a4-89c3-f1f93cce7382)

Remove logic for this & the UI as well

**Comment by assimhabeek** [comment]
via Hubstaff
User: assim

Project: platform - https://app.hubstaff.com/projects/2961404
Date Range: 04/20/24 - 04/20/24
Work session total: 0:16:10
Billable: Yes

Grand total: 0:16:10
