### ISSUE TITLE
Some kind of loop 

### ISSUE THREAD

**Issue by webberwang** [codelab-app/platform#3340]
## Video/Screenshot Showing Bug

![Cursor_and_Home](https://github.com/codelab-app/platform/assets/26264925/5492dc78-284a-498c-84fd-6af98980f0f2)

basic page with a div with children text via props inspector

**Comment by assimhabeek** [comment]
The reason of this loop is passing `routerService.query` inside mobx. to reproduce either trigger a `fast-refresh` or a router navigation.

**Comment by webberwang** [comment]
> The reason of this loop is passing `routerService.query` inside mobx. to reproduce either trigger a `fast-refresh` or a router navigation.

I see, would need to memoize it somehow?
