### ISSUE TITLE
Ux improvement: convert right panel to collapsible/expandable sidebar

### ISSUE THREAD

**Issue by vladyslav-polishchuk** [codelab-app/platform#3382]
## What Feature Can Be Enhanced?

This is a suggestion to convert right panel to a collapsible sidebar. This would make it more consistent with the left sidebar, and would also allow to save some horizontal space for users, since the right panel is complementary and is not used all the time

<img width="1728" alt="Screenshot 2024-05-25 at 09 28 46" src="https://github.com/codelab-app/platform/assets/74900868/0191595e-b655-431c-bb55-023a4a0ad4cf">

@webberwang , what do you think?

**Comment by webberwang** [comment]
Makes sense, would be good enhancement

**Comment by mohasarc** [comment]
via Hubstaff
User: Mohammed S Yaseen

Project: platform - https://app.hubstaff.com/projects/2961404
Date Range: 05/28/24 - 06/09/24
Work session total: 15:39:11
Billable: Yes

Grand total: 15:39:11
